<?php

namespace W3build\TranslateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MsgIdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsgIdRepository extends EntityRepository
{
}
