<?php

namespace W3build\TranslateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MsgStrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsgStrRepository extends EntityRepository
{
}
